---
- name: Ensure install directory exists
  ansible.builtin.file:
    path: "{{ outliness_install_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Get and unarchive outline-ss-server binary
  ansible.builtin.unarchive:
    src: "{{ outliness_download_url }}"
    dest: "{{ outliness_install_dir }}"
    remote_src: true
  notify: Restart outline-ss-server

- name: Create outline-ss-server systemd service
  ansible.builtin.template:
    src: outline-ss-server.service.j2
    dest: /etc/systemd/system/outline-ss-server.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart outline-ss-server
